// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwWUmVIhtgvca0IOC5xN3RaNuQJuLwk4',
    appId: '1:716655018735:web:bd666cec3c6b166552d11a',
    messagingSenderId: '716655018735',
    projectId: 'madapp-f7734',
    authDomain: 'madapp-f7734.firebaseapp.com',
    storageBucket: 'madapp-f7734.firebasestorage.app',
    measurementId: 'G-LXEZ46JLXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeYz3jlThd0Oynn-ZxUHIyu-MrJV5noxY',
    appId: '1:716655018735:android:bb0bf3d3bb6d6e3752d11a',
    messagingSenderId: '716655018735',
    projectId: 'madapp-f7734',
    storageBucket: 'madapp-f7734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0vA5SNlSKBZYubzUEseMQV30LnsWMhQ',
    appId: '1:716655018735:ios:f54c44efb387a28452d11a',
    messagingSenderId: '716655018735',
    projectId: 'madapp-f7734',
    storageBucket: 'madapp-f7734.firebasestorage.app',
    iosBundleId: 'com.example.madapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd0vA5SNlSKBZYubzUEseMQV30LnsWMhQ',
    appId: '1:716655018735:ios:f54c44efb387a28452d11a',
    messagingSenderId: '716655018735',
    projectId: 'madapp-f7734',
    storageBucket: 'madapp-f7734.firebasestorage.app',
    iosBundleId: 'com.example.madapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQwWUmVIhtgvca0IOC5xN3RaNuQJuLwk4',
    appId: '1:716655018735:web:c8f09e92962cfc7c52d11a',
    messagingSenderId: '716655018735',
    projectId: 'madapp-f7734',
    authDomain: 'madapp-f7734.firebaseapp.com',
    storageBucket: 'madapp-f7734.firebasestorage.app',
    measurementId: 'G-Q5KXBZZ5ZM',
  );
}
